apiVersion: v1
kind: Secret
metadata:
  name: travel-go-secrets
  namespace: travel-go
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "Akshat762@"
  POSTGRES_DB: "travel"
  DATABASE_URL: "postgresql://postgres:Akshat762@22222@postgres:5432/travel"
  DB_CONNECTION: "postgresql://postgres:Akshat762@@postgres:5432/travel"
  SECRET_KEY: "your_secret"
  ALGORITHM: "HS256"
  EXP_TIME: "20"
  RAZORPAY_KEY_ID: rzp_test_SZj4fARrNO1A0S
  RAZORPAY_KEY_SECRET: ari3U2xnrEvr86AUfi7uE1l6